### ISSUE TITLE
Link is broken - https://docs.helix-editor.com/master

### ISSUE THREAD

**Issue by RLHerbert** [helix-editor/website#24]
Tried to access https://docs.helix-editor.com/master/themes.html#inheritance, from the 22.12 release notes, but got 404.

**Comment by the-mikedavis** [comment]
The link resolves for me (https://docs.helix-editor.com/master/themes.html#inheritance) when clicking from there and the release notes. Maybe something is cached?

**Comment by RLHerbert** [comment]
Possibly. It has resolved itself in any case.
