### ISSUE TITLE
Add "space" mode remapping instructions

### ISSUE THREAD

**Issue by dkotik** [helix-editor/website#25]
This issue should really be added to the documentation:

"How to remap keys into the 'space' mode?"

https://github.com/helix-editor/helix/discussions/2844

I would have submitted a PR myself. However, it appears to me that `keys.insert` or other modes may be possible as well? I don't know. I would be good to have an exhaustive explanation added. I found the discussion by googling my problem after looking through the docs first.

**Comment by the-mikedavis** [comment]
This is covered by https://github.com/helix-editor/helix/issues/4811 in the helix repo. (This helix-editor/website repo is the source for the `helix-editor.com` site while the source for the `docs.helix-editor.com` site is in helix-editor/helix)
