### ISSUE TITLE
Add RSS link to News page

### ISSUE THREAD

**Issue by LinkSake** [helix-editor/website#45]
I took me a while to realize that the RSS feed was under `/atom.xml`. I think it's pretty standard to have some link pointing to it on the news page or the footer, something like this:

![Screenshot 2024-07-29 at 12 05 23](https://github.com/user-attachments/assets/c2bbecb7-8a75-4d89-aa19-78d24bcaf14c)

Reading the Zola docs it would just be a matter to add a link with  `href="{{ get_url(path="atom.xml", trailing_slash=false) }}"` since the `base.html` file already has the feeds autodiscovery option.

**Comment by LinkSake** [comment]
Code could be something like this

```html
<style>
.title-section {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
   
  a {
    margin-block-start: 1.66em;
    margin-block-end: 1.66em;
    text-align: end;  
  }
}

...
</style>
<div class="title-section">
  <h1>
   {{ section.title }}
  </h1>
  <a href="{{ get_url(path="atom.xml", trailing_slash=false) }}">
    RSS
  </a>
</div>

...
```

**Comment by pickfire** [comment]
Don't we already have this?
```html
templates/base.html
16:      <link rel="alternate" type="application/atom+xml" title="Atom" href="{{ get_url(path="atom.xml", trailing_slash=false) }}">
```
Feel free to submit a PR for this.

**Comment by mweinelt** [comment]
https://helix-editor.com/atom.xml returns a 404 for me.

**Comment by leo-unglaub** [comment]
> https://helix-editor.com/atom.xml returns a 404 for me. It used to work 5 hours ago.

Do you still have that issue? It seams to work fine for me.

**Comment by mweinelt** [comment]
Was resolved through https://github.com/helix-editor/website/pull/48
