### ISSUE TITLE
News Feed doesn't exist anymore (HTTP 404)

### ISSUE THREAD

**Issue by TobTobXX** [helix-editor/website#49]
My feed reader showed helix-editor.com erroring out with the following message:
```
Resource not found (404), this feed doesn't exist anymore, check the feed URL
```

I tried removing and re-adding the feed, but the same error shows up.
Did RSS get deactivated?

**Comment by gabydd** [comment]
Should be fixed by https://github.com/helix-editor/website/pull/48
