### ISSUE TITLE
this was quite confusing to read because  there are no `select_` variants of command. It's just how some things are named.

### ISSUE THREAD

**Issue by TSDell2023** [helix-editor/website#54]
this was quite confusing to read because  there are no `select_` variants of command. It's just how some things are named. 

Making selected variants of the `goto_*` commands sounds like #5127. However I am not sure that would cover what you want. since when multiple lines are selected that would also remove the selection from the previous line.

> This worked for a single line, but by necessity, if I had any other lines selected, it would deselect them. I don't believe there's a key combination that would replicate my ideal behavior here, where it wouldn't deselect previous lines, but it also wouldn't care about where you started the selection.

This is what `X` is for, otherwise `vgl` or `vgh` work too (depending on direction of the selection)

_Originally posted by @pascalkuthe in https://github.com/helix-editor/helix/discussions/12211#discussioncomment-11495958_

**Comment by pascalkuthe** [comment]
so what is the issue here?

**Comment by gabydd** [comment]
Might be a mistake or bot I am going to close this cause it's just a copy of pascals comment which has no relation to the website

**Comment by gabydd** [comment]
(my bad I cant close things in this repo)
