### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by declancm** [helix-editor/website#7]
![image](https://user-images.githubusercontent.com/90937622/161962337-f5ddae19-f6dd-41d3-961f-cc25455b526c.png)

On the helix website within the 'keymaps' tab, i think the text for `delete_char_forward` should read "Delete next char" 😬

**Comment by the-mikedavis** [comment]
Actually those keymaps stuff live in helix-editor/helix so the original issue was in the right spot. Looks like this was fixed in https://github.com/helix-editor/helix/pull/1180 in any case
